(function(){'use strict';const $=id=>document.getElementById(id),en=document.documentElement.lang==='en',say=(ja,english)=>en?english:ja;let epoch=0,book=null,rendition=null,busy=false;
function status(text){$('status').textContent=text}function controls(enabled){for(const id of ['prev','next','toc','language-en','language-ja'])$(id).disabled=!enabled}
function destroy(){busy=false;$('open-sample').disabled=false;if(rendition){try{rendition.destroy()}catch{}rendition=null}if(book){try{book.destroy()}catch{}book=null}$('viewer').replaceChildren();$('toc').replaceChildren();$('chapter-links').replaceChildren();$('book-title').textContent='';controls(false);$('reader').hidden=true;$('external-dialog').close()}
function xml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('XML entities are unsupported');const d=new DOMParser().parseFromString(text,'application/xml');if(d.querySelector('parsererror'))throw Error('Invalid EPUB XML');return d}
async function validate(buffer){const info=EpubGuard.inspect(buffer);const sizes=new Map(info.entries.map(e=>[e.name,e.expanded]));const zip=await JSZip.loadAsync(buffer);const text=async name=>{if(!sizes.has(name)||sizes.get(name)>2*1024*1024||!zip.file(name))throw Error('Missing or oversized EPUB metadata');const s=await zip.file(name).async('string');if(s.length>2*1024*1024)throw Error('Oversized EPUB metadata');return s};const container=xml(await text('META-INF/container.xml'));const path=container.getElementsByTagName('rootfile')[0]?.getAttribute('full-path');if(!path||!sizes.has(path))throw Error('Missing package');const opf=xml(await text(path));const items=Array.from(opf.getElementsByTagName('item'));if(!items.length)throw Error('Missing manifest');for(const item of items){const p=EpubGuard.localResource(item.getAttribute('href'),path);if(!sizes.has(p)||!zip.file(p))throw Error('External or missing EPUB resource')}return {info,zip,path}}
function sanitize(doc){const head=doc.head||doc.getElementsByTagName('head')[0];if(!head)throw Error('Missing chapter head');doc.querySelectorAll('script,iframe,object,embed,form,input,button,textarea,select,meta[http-equiv]').forEach(n=>n.remove());doc.querySelectorAll('*').forEach(n=>{for(const a of Array.from(n.attributes)){if(/^on/i.test(a.name)||a.name==='srcdoc'||a.name==='srcset')n.removeAttribute(a.name)}if(n.tagName.toLowerCase()==='a'){const href=(n.getAttribute('href')||'').trim();n.setAttribute('href',href);if(/^(javascript:|data:|blob:|file:|mailto:|tel:)/i.test(href))n.removeAttribute('href');n.removeAttribute('target');n.removeAttribute('download')}});const meta=doc.createElement('meta');meta.setAttribute('http-equiv','Content-Security-Policy');meta.setAttribute('content',"default-src 'none'; img-src blob: data:; style-src 'unsafe-inline' blob: data:; font-src blob: data:; connect-src 'none'; form-action 'none'; object-src 'none'");head.insertBefore(meta,head.firstChild)}
function confirmExternal(url){$('external-url').textContent=url;$('external-open').href=url;$('external-dialog').showModal()}
function captureLinks(contents){const links=$('chapter-links');links.replaceChildren();const base=book?.spine.spineItems[contents.sectionIndex]?.href;if(base){for(const anchor of contents.document.querySelectorAll('a[href]')){const href=anchor.getAttribute('href');if(EpubGuard.externalURL(href)||!href)continue;try{const target=EpubGuard.localResource(href,base)+(href.includes('#')?'#'+href.split('#').slice(1).join('#'):'');if(!book.spine.get(target.split('#')[0]))continue;const b=document.createElement('button');b.type='button';b.textContent=anchor.textContent;b.onclick=()=>move(()=>rendition.display(target));links.append(b)}catch{}}}contents.document.addEventListener('click',event=>{const anchor=event.target.closest?.('a[href]');if(!anchor)return;const url=EpubGuard.externalURL(anchor.getAttribute('href'));if(url){event.preventDefault();event.stopImmediatePropagation();confirmExternal(url);return}event.preventDefault();event.stopImmediatePropagation();try{const href=anchor.getAttribute('href'),base=book?.spine.spineItems[contents.sectionIndex]?.href;if(!base||!href)throw Error();const target=EpubGuard.localResource(href,base)+(href.includes('#')?'#'+href.split('#').slice(1).join('#'):'');move(()=>rendition.display(target))}catch{status(say('目次から読みたい章を選んでください。','Choose the chapter from Contents.'))}},true)}
async function open(buffer,name,startTarget,token){let ownBook=null;try{await validate(buffer);if(token!==epoch)return;destroy();ownBook=ePub(undefined,{replacements:'blobUrl'});book=ownBook;ownBook.spine.hooks.content.register(sanitize);await ownBook.open(buffer,'binary');if(token!==epoch){if(book===ownBook)destroy();return}await ownBook.ready;if(token!==epoch)return;
 rendition=ownBook.renderTo('viewer',{width:'100%',height:'100%',flow:'scrolled-doc',spread:'none',allowScriptedContent:false,allowPopups:false});rendition.hooks.content.register(captureLinks);rendition.on('displayError',()=>{if(token===epoch){destroy();status(say('このEPUBを表示できません。別のEPUBアプリでも確認してください。','This EPUB could not be displayed. Try a separate EPUB app as well.'))}});
 const nav=await ownBook.loaded.navigation;if(token!==epoch)return;function add(items,depth=0){for(const item of items){const option=document.createElement('option');option.value=item.href;option.textContent='　'.repeat(depth)+item.label;$('toc').append(option);if(item.subitems?.length)add(item.subitems,depth+1)}}add(nav.toc||[]);$('book-title').textContent=ownBook.packaging.metadata.title||name;$('reader').hidden=false;
 await rendition.display(startTarget||undefined);if(token!==epoch)return;controls(true);status(say('このブラウザで開けました。目次から日本語・Englishの章を選べます。','Opened in this browser. Choose Japanese or English chapters from Contents.'));rendition.on('relocated',loc=>{if(token!==epoch)return;const href=loc.start?.href;if(href){const option=Array.from($('toc').options).find(o=>o.value.split('#')[0]===href.split('#')[0]);if(option)$('toc').value=option.value}});
 }catch(err){if(token!==epoch)return;destroy();status(say('開けませんでした。25MB以内の、外部素材に依存しない通常のEPUBを選んでください。','Could not open this file. Choose a standard EPUB up to 25 MB with its resources included.'))}finally{if(token===epoch){busy=false;$('open-sample').disabled=false}}}
async function move(action){if(!rendition||busy)return;const token=epoch;busy=true;try{await action();}catch{status(say('この位置を表示できません。目次から別の章を選んでください。','Could not display this location. Choose another chapter from Contents.'))}finally{if(token===epoch)busy=false}}
$('file').onchange=async()=>{const f=$('file').files[0],token=++epoch;destroy();if(!f){status('');return}if(!/\.epub$/i.test(f.name)||!f.size||f.size>EpubGuard.MAX){status(say('25MB以内の.epubファイルを選んでください。','Choose an .epub file up to 25 MB.'));return}busy=true;status(say('端末内でEPUBを開いています…','Opening the EPUB on this device…'));try{const buffer=await f.arrayBuffer();if(token===epoch)await open(buffer,f.name,null,token)}catch{if(token===epoch){busy=false;status(say('ファイルを読み取れません。','Could not read the file.'))}}};
$('open-sample').onclick=async()=>{const token=++epoch;destroy();busy=true;$('open-sample').disabled=true;status(say('無料の第一場面を開いています…','Opening the free first scene…'));try{const response=await fetch('harbor-lights-first-scene-bilingual.epub',{credentials:'omit'});if(!response.ok)throw Error();const buffer=await response.arrayBuffer();if(token===epoch)await open(buffer,'Free first scene','en-0.xhtml',token)}catch{if(token===epoch){busy=false;$('open-sample').disabled=false;status(say('見本を開けません。EPUBをダウンロードし、ファイル選択で開いてください。','Could not open the sample. Download the EPUB and use the file picker.'))}}};
$('prev').onclick=()=>move(()=>rendition.prev());$('next').onclick=()=>move(()=>rendition.next());$('toc').onchange=()=>{const href=$('toc').value,url=EpubGuard.externalURL(href);if(url){confirmExternal(url);return}if(/^[a-z][a-z\d+.-]*:/i.test(href)){status(say('この目次のリンクには対応していません。','This Contents link is unsupported.'));return}move(()=>rendition.display(href))};for(const lang of ['en','ja'])$('language-'+lang).onclick=()=>{if(!book)return;const item=book.spine.spineItems.find(s=>new RegExp('(?:^|/)'+lang+'-').test(s.href));if(item)move(()=>rendition.display(item.href));else status(say('このEPUBには対応する言語の章が見つかりません。目次から選んでください。','No matching language chapter was found. Use Contents.'))};$('external-cancel').onclick=()=>$('external-dialog').close();$('external-open').onclick=()=>$('external-dialog').close();window.addEventListener('pagehide',()=>{epoch++;destroy()});controls(false);
})();
