(function(){'use strict';
const $=id=>document.getElementById(id),en=document.documentElement.lang==='en',say=(ja,english)=>en?english:ja;
let generation=0,jsonLoadEpoch=0,jsonLoading=false,report='',checked=null,previewURL=null,previewLanguage=en?'en':'ja';const imageURLs=new Set;let order=[0,1,2],termsEpoch=0,termsLoadEpoch=0,termsLoading=false;
function releaseImageURL(url){if(imageURLs.delete(url))URL.revokeObjectURL(url)}
function save(name,data,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function clear(){checked=null;$('result').hidden=true;$('buy').hidden=true;$('pack').disabled=true;$('pack-epub').disabled=true;$('confirm-order').disabled=true;$('preview').hidden=true;$('preview-image').removeAttribute('src');for(const url of imageURLs)releaseImageURL(url);previewURL=null;}
function changed(){generation++;clear()}
function renderPreview(){if(!checked)return;const box=$('all-scenes');box.replaceChildren();checked.story.scenes.forEach((scene,i)=>{const article=document.createElement('article');article.className='own-scene';const figure=document.createElement('figure'),image=document.createElement('img');image.src=checked.urls[i];image.alt=say('場面'+(i+1)+'に割り当てた作者の絵','Your artwork assigned to scene '+(i+1));figure.append(image);const text=document.createElement('div'),title=document.createElement('h3'),body=document.createElement('p'),name=document.createElement('p');title.textContent=previewLanguage==='en'?(scene.title_en||'Scene '+(i+1)):scene.title;body.textContent=scene[previewLanguage];body.lang=previewLanguage;name.textContent=checked.files[i].name+' → '+CreatorReady.NAMES[i];text.append(title,body,name);for(const [direction,label]of [[-1,say('一つ前の場面へ','Move to previous scene')],[1,say('一つ後の場面へ','Move to next scene')]]){const button=document.createElement('button');button.type='button';button.textContent=label;button.disabled=i+direction<0||i+direction>2;button.onclick=()=>{const next=i+direction;[order[i],order[next]]=[order[next],order[i]];changed();$('form').requestSubmit();};text.append(button);}article.append(figure,text);box.append(article);});$('preview-ja').setAttribute('aria-pressed',String(previewLanguage==='ja'));$('preview-en').setAttribute('aria-pressed',String(previewLanguage==='en'));}
function refreshTerms(){try{CreatorReady.terms($('terms').value);$('save-terms').disabled=termsLoading;$('pack-epub').disabled=termsLoading||!checked||!checked.confirmed;$('terms-status').textContent=say('自分の条件文を保存できます。権利や法的な有効性は判定しません。','Your terms can be saved. This does not assess rights or legal validity.');}catch(error){$('save-terms').disabled=true;$('pack-epub').disabled=true;$('terms-status').textContent=$('terms').value?say('条件文は空欄以外で、UTF-8の100,000バイト以内にしてください。','Use nonempty terms up to 100,000 UTF-8 bytes.'):say('EPUB・納品用には、自分の利用条件を記入してください。HTML用の入力ZIPは条件文なしでも保存できます。','Write your own terms for EPUB and delivery. You can save the HTML input ZIP without them.');}}
async function pngCheck(file,name){if(!file)return name+say('が未選択',' is not selected');if(!file.size||file.size>15*1024*1024)return name+say('は1バイト〜15MiBが必要',' must be 1 byte–15 MiB');const b=new Uint8Array(await file.slice(0,24).arrayBuffer());if(b.length!==24||![137,80,78,71,13,10,26,10].every((x,i)=>b[i]===x)||String.fromCharCode(...b.slice(12,16))!=='IHDR')return name+say('はPNGヘッダーが不正',' has an invalid PNG header');const v=new DataView(b.buffer,b.byteOffset,b.byteLength);if(v.getUint32(16)!==1024||v.getUint32(20)!==1536)return name+say('は1024×1536が必要',' must be 1024×1536');return ''}
async function decodePNG(file){const u=URL.createObjectURL(file);imageURLs.add(u);try{const image=new Image();image.src=u;await image.decode();if(image.naturalWidth!==1024||image.naturalHeight!==1536)throw Error();return u}catch{releaseImageURL(u);throw Error(file.name+say('を1024×1536の画像として表示できません。PNGを確認してください。',' could not be decoded as a 1024×1536 image. Check the PNG.'))}}
$('form').addEventListener('input',changed);$('form').addEventListener('change',changed);for(const id of ['station','rain','harbor'])$(id).addEventListener('change',()=>{order=[0,1,2];});
$('example').onclick=()=>{if(jsonLoading)return;$('json').value=JSON.stringify(window.ReaderExample,null,2);changed()};
$('form').onsubmit=async e=>{e.preventDefault();if(jsonLoading)return;const token=++generation;clear();const files=CreatorReady.assign(['station','rain','harbor'].map(k=>$(k).files[0]),order);let story,errs=[],urls=[];
 try{const text=$('json').value;if(text.length>150000)throw Error();story=JSON.parse(text);errs=ReaderInput.validate(story,en?'en':'ja')}catch{errs=[say('作品JSONを読み取れません。オブジェクト形式・文字数を確認してください。','Cannot read the story JSON. Check the object format and length.')]} 
 try{errs.push(...(await Promise.all(files.map((f,i)=>pngCheck(f,['station.png','rain.png','harbor.png'][i])))).filter(Boolean));if(!errs.length)for(let i=0;i<files.length;i++){const decoded=await decodePNG(files[i]);if(token!==generation){releaseImageURL(decoded);for(const old of urls)releaseImageURL(old);return}urls.push(decoded);}}catch(err){errs.push(err.message||say('ファイルを読み取れません。','Cannot read the files.'))}
 if(token!==generation){for(const url of urls)releaseImageURL(url);return}
 if(!$('python').checked)errs.push(say('Python 3.10実行環境が未確認','Python 3.10 environment is unconfirmed'));if(!$('rights').checked)errs.push(say('素材の利用権が未確認','Asset permission is unconfirmed'));
 report=errs.length?say('不足\n','Missing requirements\n')+errs.join('\n'):say('構造・PNG寸法を確認し、3枚すべてを画像として読み取れました。\n実際の生成実行・画質・権利・販売審査を保証する結果ではありません。','Structure and PNG dimensions passed; all three images decoded successfully.\nThis does not guarantee successful production, image quality, rights or shop acceptance.');
 $('heading').textContent=errs.length?say('購入前に整えたい部分','Requirements to resolve before buying'):say('自分の作品を試読する','Preview your own story');$('report').textContent=report;$('result').hidden=false;$('buy').hidden=true;
 if(errs.length){for(const url of urls)releaseImageURL(url);return}checked={story,files,urls,token,confirmed:false};renderPreview();$('preview').hidden=false;$('confirm-order').disabled=false;$('order-status').textContent=say('3場面と絵を見比べ、必要なら入れ替えてから順序を確定してください。','Compare all three scenes and images, swap if needed, then confirm their order.');refreshTerms();
};
$('download').onclick=()=>save('reader-input-check.txt',report,'text/plain;charset=utf-8');
async function pack(includeTerms){const snapshot=checked,epoch=termsEpoch;if(!snapshot||!snapshot.confirmed||snapshot.token!==generation||jsonLoading)return;let rights;try{if(includeTerms&&termsLoading)return;if(includeTerms)rights=CreatorReady.terms($('terms').value);}catch{return}$('pack').disabled=true;$('pack-epub').disabled=true;try{const bytes=await Promise.all(snapshot.files.map(f=>f.arrayBuffer()));if(checked!==snapshot||snapshot.token!==generation||jsonLoading||(includeTerms&&epoch!==termsEpoch))return;const files=[{name:'content.json',data:new TextEncoder().encode(JSON.stringify(snapshot.story,null,2)+'\n')},...bytes.map((b,i)=>({name:CreatorReady.NAMES[i],data:new Uint8Array(b)}))];if(includeTerms)files.push({name:'rights.txt',data:rights});save(includeTerms?'reader-epub-inputs.zip':'reader-inputs.zip',CreatorReady.zip(files),'application/zip');}catch{$('report').textContent=say('ZIPを作成できませんでした。素材を再確認してください。','Could not create the ZIP. Check the assets again.');}finally{if(checked===snapshot&&snapshot.token===generation){$('pack').disabled=false;refreshTerms();}}}
$('pack').onclick=()=>pack(false);$('pack-epub').onclick=()=>pack(true);
$('confirm-order').onclick=()=>{if(!checked||checked.token!==generation)return;checked.confirmed=true;$('pack').disabled=false;$('buy').hidden=false;$('order-status').textContent=say('この順序で入力ZIPを保存できます。絵の内容が物語に合うかは作者自身の確認です。','You can save the input ZIP in this order. Whether the artwork fits the story is your own judgment.');refreshTerms();};
$('terms').oninput=()=>{termsEpoch++;termsLoadEpoch++;termsLoading=false;refreshTerms();};$('save-terms').onclick=()=>{if(termsLoading)return;try{save('rights.txt',CreatorReady.terms($('terms').value),'text/plain;charset=utf-8');}catch{refreshTerms();}};
$('terms-file').onchange=async()=>{const token=++termsLoadEpoch;termsEpoch++;termsLoading=true;$('pack-epub').disabled=true;$('save-terms').disabled=true;const f=$('terms-file').files[0];if(!f){termsLoading=false;refreshTerms();return}try{if(f.size>100000)throw Error();const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());CreatorReady.terms(text);if(token!==termsLoadEpoch)return;$('terms').value=text;termsEpoch++;termsLoading=false;refreshTerms();}catch{if(token===termsLoadEpoch){termsLoading=false;refreshTerms();$('terms-status').textContent=say('UTF-8の空欄以外のTXT（100,000バイト以内）を選んでください。現在の条件文は保持しています。','Choose a nonempty UTF-8 TXT up to 100,000 bytes. Your current terms are preserved.');}}finally{if(token===termsLoadEpoch)$('terms-file').value='';}};
refreshTerms();
$('preview-ja').onclick=()=>{previewLanguage='ja';renderPreview()};$('preview-en').onclick=()=>{previewLanguage='en';renderPreview()};
$('json-file').onchange=async()=>{const token=++jsonLoadEpoch;changed();const f=$('json-file').files[0];jsonLoading=!!f;const submit=$('check');for(const el of [submit,$('json'),$('example')])el.disabled=jsonLoading;if(!f)return;
 try{if(f.size>600000)throw Error();const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(text.length>150000)throw Error();if(token!==jsonLoadEpoch)return;$('json').value=text}catch{if(token===jsonLoadEpoch){report=say('JSONはUTF-8で15万字以内にしてください。現在の入力は保持しています。','Use UTF-8 JSON up to 150,000 characters. Your current input is preserved.');$('report').textContent=report;$('result').hidden=false}}finally{if(token===jsonLoadEpoch){jsonLoading=false;for(const el of [submit,$('json'),$('example')])el.disabled=false}}
};
window.addEventListener('pagehide',()=>{generation++;for(const url of imageURLs)releaseImageURL(url)});
})();
