'use strict';const $=id=>document.getElementById(id);
function clearResult(){$('result').hidden=true;$('buy').hidden=true}
function setup(){const read=$('kind').value==='read';$('format').replaceChildren();for(const [value,label]of read?[['html','日英HTMLリーダー（ZIP）'],['epub','日英EPUB（電子書籍）']]:[['html','日英HTMLゲーム（ZIP）'],['pdf','英語の印刷用PDF']]){const o=document.createElement('option');o.value=value;o.textContent=label;$('format').append(o)}$('can').checked=false;environment();clearResult()}
function environment(){const kind=$('kind').value,format=$('format').value;$('environment-label').textContent=format==='epub'?'相手のEPUBアプリで無料の第一場面を開けた':format==='pdf'?'相手は英語PDFを読め、A4・片面・原寸で自分で印刷できる':'相手は無料ZIPを解凍し、ローカルHTMLとJavaScriptを使える';$('can').checked=false;clearResult()}
$('form').addEventListener('input',clearResult);$('kind').onchange=setup;$('format').onchange=environment;$('language').onchange=()=>{$('can').checked=false;clearResult()};
$('form').onsubmit=e=>{e.preventDefault();const kind=$('kind').value,format=$('format').value,lang=$('language').value,read=kind==='read';const supported=['ja','en'].includes(lang)&&((read&&['html','epub'].includes(format))||(kind==='play'&&(format==='html'||(format==='pdf'&&lang==='en'))));const ok=supported&&$('can').checked&&$('permission').checked;$('heading').textContent=read?'港の灯りを持ち帰る':'Three Harbor Signs / 港に残った三つのしるし';let trial,description;
 if(read&&format==='epub'){trial='../epub-reader/'+(lang==='en'?'en.html':'');description='日英の全3場面・両結末を収録するEPUB。無料見本を相手のEPUBアプリで試してください。'}
 else if(read){trial='../viewer-trial/';description='日英3場面・両結末と3画像のHTML読書版。無料の保存用HTMLを相手の端末で試してください。'}
 else if(format==='pdf'){trial='../print-and-play/';description=lang==='en'?'英語のみの13ページPDF。無料5ページの完結ケースで、読めるか・印刷できるかを試してください。日英HTMLも同じ購入に含まれます。':'印刷用PDFは英語のみです。日本語で紙遊びができる商品としては案内しません。日本語HTMLなら形式を変更し、無料ゲームを試してください。'}
 else{trial=lang==='en'?'../harbor-first-case-en/':'../harbor-first-case/';description='同じ3問の日英HTMLゲーム。無料ケースと保存用ZIPを試し、カードを閉じて端末を渡してください。'}
 $('detail').textContent=description+(ok?' 最低US$3。正規のギフト画面で商品・条件・最終額を確認してください。':' 相手の環境・試用・連絡の確認が済むまで購入リンクは表示しません。');$('trial').href=trial;$('buy').href='https://tiny-deduction-lab.itch.io/'+(read?'harbor-lights':'three-harbor-signs');$('result').hidden=false;$('buy').hidden=!ok};setup();
