(function(){'use strict';
const $=id=>document.getElementById(id),en=document.documentElement.lang==='en',say=(ja,english)=>en?english:ja,{keys,composeStory,makeDraft,restore}=StoryComposer;let loadEpoch=0;
const raw=()=>Object.fromEntries(keys.map(k=>[k,$(k).value]));
function save(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function changed(){loadEpoch++;$('result').hidden=true;$('load-status').textContent=''}
$('example').onclick=()=>{changed();for(const k of keys)$(k).value=k.endsWith('_title_en')?'':k.endsWith('_en')?'An original fictional scene.':k.startsWith('choice')?'この結末を選ぶ':k==='english_title'?'A paper lantern':k==='disclosure'?say('架空の人物と場所。AIを用いた入力例。','Fictional people and places. AI-assisted input example.'):'架空の物語の入力例'};
$('form').addEventListener('input',changed);
$('save-draft').onclick=()=>{try{save('story-draft.json',makeDraft(raw()));$('load-status').textContent=say('空欄を含めて途中稿を保存しました。続きはこのファイルを読み込んでください。','Saved the draft with blank fields preserved. Load this file to continue.')}catch(err){$('load-status').textContent=say('途中稿を保存できません。','Could not save the draft. ')+err.message}};
$('load-file').onchange=async()=>{const token=++loadEpoch,f=$('load-file').files[0];if(!f)return;$('load-status').textContent=say('ファイルを読み込み中…','Reading the file…');try{if(!f.size||f.size>700000)throw Error('File size');const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(text.length>180000)throw Error('File length');const v=restore(JSON.parse(text));if(token!==loadEpoch)return;for(const k of keys)$(k).value=v[k];$('result').hidden=true;$('load-status').textContent=say('読み込んだ作品を編集欄へ戻しました。','Loaded your story into the editing fields.')}catch{if(token===loadEpoch)$('load-status').textContent=say('読み込めません。対応する途中稿、またはこの編集欄の固定ID・順序に合う完成content.jsonを選んでください。現在の入力は保持しています。','Could not load this file. Choose a supported draft or completed content.json with this editor’s fixed IDs and order. Your current input is preserved.')}finally{if(token===loadEpoch)$('load-file').value=''}};
$('form').onsubmit=e=>{e.preventDefault();try{const d=composeStory(raw());save('content.json',d);$('report').textContent=say('3場面・2結末・対応する2選択のcontent.jsonを保存しました。入力した本文や翻訳の品質、権利、実行成功は別に確認してください。','Saved content.json with three scenes, two endings and their two choice labels. Separately verify text and translation quality, rights and successful production.');$('result').hidden=false}catch(err){$('report').textContent=say('空欄・長さを確認してください：','Check blank fields and lengths: ')+err.message;$('result').hidden=false}};
})();
