(function(root){'use strict';
const reader=typeof module!=='undefined'&&module.exports?require('../creator-input-check/reader-input.js'):root.ReaderInput;
const keys=['title','english_title','disclosure',...Array.from({length:3},(_,i)=>['title','title_en','ja','en'].map(k=>'scene'+i+'_'+k)).flat(),...Array.from({length:2},(_,i)=>['title','title_en','ja','en'].map(k=>'ending'+i+'_'+k)).flat(),...Array.from({length:2},(_,i)=>['ja','en'].map(k=>'choice'+i+'_'+k)).flat()];
const object=x=>x&&typeof x==='object'&&!Array.isArray(x),exact=(x,ks)=>object(x)&&Object.keys(x).length===ks.length&&ks.every(k=>Object.hasOwn(x,k));
const cap=k=>k==='disclosure'?2000:(k==='title'||k==='english_title'||k.includes('_title')||k.startsWith('choice'))?200:10000;
function fields(v,complete=false){if(!exact(v,keys))throw Error('Unknown or missing draft field');let length=0;for(const k of keys){if(typeof v[k]!=='string'||v[k].length>cap(k))throw Error('Invalid field or length: '+k);length+=v[k].length;if(complete&&!k.endsWith('_title_en')&&!v[k].trim())throw Error('Empty field: '+k)}if(length>150000)throw Error('Text exceeds 150,000 characters');return Object.fromEntries(keys.map(k=>[k,v[k]]))}
function composeStory(v){if(object(v))v={...Object.fromEntries(keys.filter(k=>k.endsWith('_title_en')).map(k=>[k,''])),...v};v=fields(v,true);const need=k=>v[k].trim();const sceneIds=['station','cafe','hotel'],endIds=['first','second'];const item=(kind,id,i)=>{const x={id,title:need(kind+i+'_title'),ja:need(kind+i+'_ja'),en:need(kind+i+'_en')};const title_en=need(kind+i+'_title_en');if(title_en)x.title_en=title_en;return x};return {title:need('title'),english_title:need('english_title'),disclosure:need('disclosure'),scenes:sceneIds.map((id,i)=>item('scene',id,i)),endings:endIds.map((id,i)=>item('ending',id,i)),choices:endIds.map((ending_id,i)=>({id:['one','two'][i],ending_id,label_ja:need('choice'+i+'_ja'),label_en:need('choice'+i+'_en')}))}}
function makeDraft(v){return {schema:'bilingual-story-draft',version:1,fields:fields(v)}}
function restoreContent(d){if(reader.validate(d).length)throw Error('Invalid completed story JSON');if(d.scenes.some((s,i)=>s.id!==['station','cafe','hotel'][i])||d.endings.some((s,i)=>s.id!==['first','second'][i])||d.choices.some((c,i)=>c.id!==['one','two'][i]||c.ending_id!==['first','second'][i]))throw Error('This editor needs station/cafe/hotel, first/second and their one/two choices in order');const v={title:d.title,english_title:d.english_title,disclosure:d.disclosure};for(const [group,prefix]of [['scenes','scene'],['endings','ending']])d[group].forEach((s,i)=>{for(const k of ['title','ja','en'])v[prefix+i+'_'+k]=s[k];v[prefix+i+'_title_en']=s.title_en||''});d.choices.forEach((c,i)=>{v['choice'+i+'_ja']=c.label_ja;v['choice'+i+'_en']=c.label_en});return fields(v,true)}
function restore(d){if(object(d)&&Object.hasOwn(d,'schema')){if(!exact(d,['schema','version','fields'])||d.schema!=='bilingual-story-draft'||d.version!==1)throw Error('Unsupported draft schema or version');return fields(d.fields)}return restoreContent(d)}
const api={keys,cap,composeStory,makeDraft,restore};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root){root.StoryComposer=api;root.composeStory=composeStory}
})(typeof window!=='undefined'?window:typeof globalThis!=='undefined'?globalThis:null);
